// Agent registry — the orchestrator + specialist subagents.
// Plain JS so any script can use it.
window.AGENTS = [
  {
    id: "orchestrator",
    nameKo: "오케스트레이터",
    nameEn: "Orchestrator",
    color: "#1f2937",
    glyph: "◆",
    icon: "compass",
    role: "router",
    descKo: "사용자 의도 파악 → 적합한 전문 에이전트로 라우팅",
    descEn: "Routes user intent to the right specialist agent",
  },
  {
    id: "shuttle",
    nameKo: "셔틀 에이전트",
    nameEn: "Shuttle Agent",
    color: "#2563eb",
    glyph: "🚌",
    icon: "bus",
    catKey: "cat_shuttle",
    role: "specialist",
    descKo: "셔틀버스 시간표·노선·실시간 운행 정보",
    descEn: "Shuttle schedules, routes, live status",
  },
  {
    id: "meeting",
    nameKo: "회의실 에이전트",
    nameEn: "Meeting Room Agent",
    color: "#0891b2",
    glyph: "📅",
    icon: "calendar",
    catKey: "cat_meeting",
    role: "specialist",
    descKo: "회의실 검색·예약·화상회의 셋업",
    descEn: "Find rooms, book, set up video conf",
  },
  {
    id: "benefits",
    nameKo: "복지 에이전트",
    nameEn: "Benefits Agent",
    color: "#7c3aed",
    glyph: "🎁",
    icon: "gift",
    catKey: "cat_benefits",
    role: "specialist",
    descKo: "복지포인트·복지몰·휴양시설·건강검진",
    descEn: "Welfare points, mall, resorts, checkups",
  },
  {
    id: "it",
    nameKo: "IT 에이전트",
    nameEn: "IT Agent",
    color: "#dc2626",
    glyph: "💻",
    icon: "laptop",
    catKey: "cat_it",
    role: "specialist",
    descKo: "SVPN·프린터·PC 반출·계정 권한",
    descEn: "SVPN, printer, PC carry-out, accounts",
  },
  {
    id: "training",
    nameKo: "교육 에이전트",
    nameEn: "Training Agent",
    color: "#ea580c",
    glyph: "🎓",
    icon: "grad",
    catKey: "cat_training",
    role: "specialist",
    descKo: "외부교육·세미나 신청·교육비 정산",
    descEn: "External training, seminars, reimbursement",
  },
  {
    id: "idcard",
    nameKo: "사원증 에이전트",
    nameEn: "ID Card Agent",
    color: "#059669",
    glyph: "🪪",
    icon: "card",
    catKey: "cat_idcard",
    role: "specialist",
    descKo: "사원증 발급·재발급·출입 권한",
    descEn: "ID issuance, reissue, access rights",
  },
  {
    id: "parking",
    nameKo: "주차권 에이전트",
    nameEn: "Parking Agent",
    color: "#0284c7",
    glyph: "🅿️",
    icon: "car",
    catKey: "cat_parking",
    role: "specialist",
    descKo: "방문객 주차권 등록·결재 상신",
    descEn: "Visitor parking registration & approval",
  },
  {
    id: "hr",
    nameKo: "인사 에이전트",
    nameEn: "HR Agent",
    color: "#be185d",
    glyph: "📋",
    icon: "doc",
    catKey: "cat_hr",
    role: "specialist",
    descKo: "휴가·근태·인사규정·승인 절차",
    descEn: "Leave, attendance, policy, approvals",
  },
  {
    id: "meals",
    nameKo: "식당 에이전트",
    nameEn: "Cafeteria Agent",
    color: "#ca8a04",
    glyph: "🍱",
    icon: "tray",
    catKey: "cat_meals",
    role: "specialist",
    descKo: "식단표·운영시간·외부식당 제휴",
    descEn: "Menus, hours, partner restaurants",
  },
  {
    id: "expense",
    nameKo: "비용 에이전트",
    nameEn: "Expense Agent",
    color: "#0d9488",
    glyph: "💳",
    icon: "card2",
    catKey: "cat_expense",
    role: "specialist",
    descKo: "법인카드·증빙·정산 처리",
    descEn: "Corp card, receipts, reimbursement",
  },
  {
    id: "wiki",
    nameKo: "지식 에이전트",
    nameEn: "Knowledge Agent",
    color: "#475569",
    glyph: "📚",
    icon: "book",
    catKey: "cat_wiki",
    role: "specialist",
    descKo: "사내 위키·매뉴얼·이전 답변 검색",
    descEn: "Internal wiki, manuals, prior answers",
  },
  {
    id: "general",
    nameKo: "일반 에이전트",
    nameEn: "General Agent",
    color: "#64748b",
    glyph: "💬",
    icon: "chat",
    catKey: "cat_general",
    role: "specialist",
    descKo: "분류되지 않은 요청 처리",
    descEn: "Catch-all for unclassified asks",
  },
];

window.AGENT_BY_ID = Object.fromEntries(window.AGENTS.map((a) => [a.id, a]));
window.agentName = (a) => (window.WL_LANG === "ko" ? a.nameKo : a.nameEn);
window.agentDesc = (a) => (window.WL_LANG === "ko" ? a.descKo : a.descEn);
